# Site settings
title: Nikola Mihajlovic
twitter_username: Nikolica98_
name: Nikola Mihajlovic

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Nikol1ca

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.NET MVC
 - SQL
 - CSS/HTML
 - C/C++

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: CV

#Work experience is required
roles:
 - title: Junior Software Engineer
   start: 2018
   end: Ongoing
   employer: MesaVis Electronics
   description: MesaVis Electronics was established as a company that has unique software and hardware for Thermal Furnaces. Thermal Furnaces are used to enhance certain metal parts adding a various number of different elements just as Calcium, Phosphate and others. I am an internship in this company and my role is to help a team of Software Engineers in documenting theyr software as well as manage the database.

#Education is required
education:
 - level: Diploma "Vuk Karadžić"
   date: 2016
   subject: Roulette - game of luck made in Microsoft Visual Studio IDE in C# programming language  
   school: High School "Bora Stanković"  
 - level: .NET Course
   date: Ongoing
   subject: NiCAT Cluster (Pre - Qualification Course organized by the Goverment of Republic of Serbia 2017 - 2018  
   school: Faculty of Electronics

#List of interesting Github repo/projects to include - optional
github:
 - Nikol1ca/webshop2018

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |   
   <strong>Hobbies</strong>: I love cooking, reading, runing and gaming.<br/><br/>
   <strong>Language</strong>: I have a solid knowledge of english. I know decently french and german.
